name: trpg_tool
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # 路由,状态管理
  get: ^4.6.6
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # 链式
  velocity_x: ^4.2.1
  # ui组件
  tdesign_flutter: ^0.1.7
  # 日志打印
  logger: ^2.4.0
  # 弹窗
  flutter_easyloading: ^3.0.5
  # 权限处理
  permission_handler: ^11.3.1
  # 路径提供
  path_provider: ^2.1.4
  # 键盘焦点取消
  keyboard_dismisser: ^3.0.0
  # 本地存储
  shared_preferences: ^2.3.2
  # 图片保存
  qr_flutter: ^4.1.0
  username:
    path: username
  # 音频播放
  audioplayers: ^6.1.0
  # win窗口管理
  window_manager: ^0.4.3
  # 表格
  csv: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sound/
    - assets/excel/职业.csv
