name: username
description: generate random dummy usernames(Chinese and English supported now),using top surnames and given names in recent years.
version: 0.2.3

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
